### ISSUE TITLE
Fails to detect a data URI that has parenthesis in an attribute value

### ISSUE THREAD

**Issue by erunion** [killmenot/valid-data-url#5]
```js
const parsed = parseDataUrl('data:image/svg+xml;name=foobar%20(1).svg;charset=UTF-8,some-data');

// false
```

As far as I can tell from reading the spec, parentheses should be valid characters as they're unreserved for `encodeURI()` and `encodeURIComponent()`.

**Comment by killmenot** [comment]
@erunion Hi, I will try to take a look at it on week-end. If you have a PR to fix - please submit
